name: dart_native_demo
description: Dart CLI demonstrating FFI integration with C++ and Go shared libraries.
version: 1.0.0
repository: https://github.com/phanithlim/dart-native

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  ffi: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
